### ISSUE TITLE
What's the difference between this and https://github.com/SonarSource/eslint-plugin-sonarjs

### ISSUE THREAD

**Issue by CMCDragonkai** [rx-ts/eslint-plugin-sonar#31]
Are these 2 separate plugins?

**Comment by JounQin** [comment]
There are some rules in [SonarJS](https://github.com/SonarSource/SonarJS) unavailable in [eslint-plugin-sonarjs](https://github.com/SonarSource/eslint-plugin-sonarjs), so I extract rules in `SonarJS` to this project.

Take `sonar/deprecation` as example.

And you can see the rules list at https://github.com/rx-ts/eslint-plugin-sonar#rule-list and https://github.com/SonarSource/eslint-plugin-sonarjs#rules

**Comment by CMCDragonkai** [comment]
Does this work well with Typescript projects? I already have eslint rules applied with a few TS projects, I wanted to know if there will be conflicts.

**Comment by JounQin** [comment]
It uses `typescript` inside as peer dependency, so it works well with TypeScript of course.

> I wanted to know if there will be conflicts.

I think you should try it by yourself, I use it in my own and company projects, and it works well without conflict. And if you just find conflicts, you can easily disable one of the rules from it or other eslint plugins.

**Comment by CMCDragonkai** [comment]
Cool but there seems to be some rules that are in sonarjs and not in this repo like for example https://github.com/SonarSource/eslint-plugin-sonarjs/blob/master/docs/rules/cognitive-complexity.md. I didn't see that mentioned in your README.md.

**Comment by JounQin** [comment]
[SonarJS](https://github.com/SonarSource/SonarJS) and [eslint-plugin-sonarjs](https://github.com/SonarSource/eslint-plugin-sonarjs) are different, this plugin extracts rules from `SonarJS` which could be considered as additional rules.

**Comment by JounQin** [comment]
Now that https://github.com/SonarSource/eslint-plugin-sonarjs is deprecated, `eslint-plugin-sonar` can be sunset.
